#spring.datasource.url=jdbc:h2:mem:beermktp
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2


# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:beermktp
    username: admin
    password: admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: '/h2'
  data:
    rest.defaultMediaType: application/json
# Server configuration
server:
  port: 8080